### ISSUE TITLE
Extra Steps Required

### ISSUE THREAD

**Issue by pokedpeter** [Richard-W/curl-vala#2]
I had to do the following extra steps in order to successfully run the examples:

- Pass `-X -lcurl` to the valac compiler - to avoid undefined references
- Run `ldconfig` after installing the library to update the linkers to dynamic libraries - so the generated .so file could be found.

Thanks.

**Comment by Richard-W** [comment]
I can not reproduce your issue with needing to link -lcurl.
```
$ ldd libcurl-vala.so | grep curl
libcurl.so.4 => /lib64/libcurl.so.4 (0x00007fbc5ce1b000)
```

When testing i ran into a similar issue though, because i installed the lib to `/usr/local`. `pkg-config` seems to fail silently when called by valac. Try setting `LD_LIBRARY_PATH=/usr/local/lib` and `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig` when calling valac and see if that solves your issue.

The issue with ldconfig also seems to have to do with the prefix: https://cmake.org/pipermail/cmake/2007-February/013032.html

**Comment by pokedpeter** [comment]
Thanks for the feedback. I guess you can close this now.

Perhaps I installed curl differently as it put `libcurl.so` files into `/usr/lib/x86_64-linux-gnu` and it doesn't show up when I grep `libcurl-vala.so`.  (This is on a fresh install of Elementary Freya 0.3.1)
